"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";
import { generateV3Baseline, humanizePlanningIssue, toV3Request, validateV3Baseline, type ScenarioProfile, type V3Result } from "@/modules/machine-load-v3/domain";
import type { ProgramSnapshot } from "@/modules/machine-load-v2/domain";
import { buildPlanningTimeline, configForOrderCount, createPlanningState, inspectCandidates, planWithLookAhead, planningResourcesFromSnapshot, type CandidateInspection, type PlanningDecision } from "@/modules/machine-load-v3/planning-engine";

const button = "rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium hover:bg-slate-50";
const profiles: Array<{ id: ScenarioProfile; label: string; description: string }> = [
  { id: "baseline", label: "Atual / baseline", description: "Preserva a carteira atual para comparação." },
  { id: "delivery", label: "Entrega", description: "Será otimizado para proteger prazos críticos." },
  { id: "efficiency", label: "Eficiência", description: "Será otimizado para reduzir espera e setups." },
  { id: "balance", label: "Equilíbrio", description: "Será otimizado para distribuir a carga." },
];

export function V3PlanningWorkspace({ snapshot }: { snapshot: ProgramSnapshot }) {
  const router = useRouter();
  const request = useMemo(() => toV3Request(snapshot.rows), [snapshot.rows]);
  const [profile, setProfile] = useState<ScenarioProfile>("baseline");
  const [result, setResult] = useState<V3Result>(() => generateV3Baseline(request));
  const [decisions, setDecisions] = useState<PlanningDecision[]>([]);
  const [planning, setPlanning] = useState(false);
  const [showDebug, setShowDebug] = useState(false);
  const [candidateDebug, setCandidateDebug] = useState<CandidateInspection[]>([]);
  const [planningStartedAt, setPlanningStartedAt] = useState<number | null>(null);
  const validation = validateV3Baseline(request, result);
  const profileInfo = profiles.find(item => item.id === profile) ?? profiles[0];
  const resources = useMemo(() => planningResourcesFromSnapshot(snapshot.resources), [snapshot.resources]);
  const timeline = useMemo(() => decisions.length && planningStartedAt !== null ? buildPlanningTimeline(createPlanningState(request.orders, planningStartedAt, resources), decisions) : [], [decisions, request.orders, resources, planningStartedAt]);
  const regenerate = () => { setResult({ ...generateV3Baseline(request), profile }); router.refresh(); };
  const generatePlanning = async () => { setPlanning(true); const startedAt = Date.now(); const planningState = createPlanningState(request.orders, startedAt, resources); const next = planWithLookAhead(planningState, configForOrderCount(request.orders.length)); const inspection = Object.keys(planningState.presses).flatMap((press) => inspectCandidates(planningState, press)); setPlanningStartedAt(startedAt); setCandidateDebug(inspection); setDecisions(next); await fetch("/api/planning-decision-logs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decisions: next.map((decision) => ({ pressCode: decision.press, selectedOrderId: decision.candidate.orderId, selectedScore: decision.score, lookAheadDepth: decision.lookAheadDepth, candidatesEvaluated: inspection.filter((item) => item.candidate.press === decision.press).length, decisionReasons: decision.reasons, penalties: decision.candidate.resourcePenalty > 0 ? [`Recursos/aquecimento: ${decision.candidate.resourcePenalty.toFixed(1)}`] : [], risksBefore: [], risksAfter: [], metadata: { engine: "deterministic-v3", profile } })) }) }).catch(() => null); setPlanning(false); };
  return <div className="space-y-5">
    <header className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-orange-600">PCP · Carga Máquina V3</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Programação global das prensas</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Carteira → elegibilidade → restrições rígidas → otimização → simulação → validação → decisão do PCP.</p></div><span className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="size-4" />Modo sombra · nada aplicado</span></div></header>
    <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-xs font-semibold text-slate-600">Perfil de comparação<select className="mt-1 block w-full rounded-xl border bg-white p-2.5 text-sm text-slate-900" value={profile} onChange={event => { const next = event.target.value as ScenarioProfile; setProfile(next); setResult({ ...generateV3Baseline(request), profile: next }); }} >{profiles.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><button type="button" className={button} onClick={regenerate}><RefreshCw className="mr-2 inline size-4" />Recalcular baseline</button><button type="button" className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800" onClick={generatePlanning} disabled={planning}>{planning ? "Calculando…" : "Gerar planejamento determinístico"}</button></div><p className="mt-3 text-xs text-slate-500">{profileInfo.description} O planejamento usa regras duras, pré-score e Look Ahead. Nada é aplicado à sequência oficial.</p></section>
    {decisions.length > 0 && <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold text-blue-950">Prévia do Look Ahead</h2><p className="text-xs text-blue-800">Decisões simuladas; a programação oficial permanece intacta.</p></div><div className="flex items-center gap-2"><button type="button" className="rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-blue-900" onClick={() => setShowDebug((value) => !value)}>{showDebug ? "Ocultar diagnóstico" : "Ver diagnóstico"}</button><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-blue-900">{decisions.length} decisões</span></div></div><div className="mt-4 grid gap-2 md:grid-cols-2">{decisions.map((decision, index) => <article key={`${decision.candidate.orderId}-${index}`} className="rounded-xl border border-blue-200 bg-white p-3"><p className="text-xs font-bold uppercase text-blue-700">{index + 1} · Prensa {decision.press}</p><p className="mt-1 font-semibold text-slate-900">{request.orders.find(order => order.id === decision.candidate.orderId)?.order ?? decision.candidate.orderId}</p><p className="text-xs text-slate-600">Score preliminar: {decision.score.toFixed(1)} · {Math.round(decision.candidate.estimatedMinutes)} min estimados</p><p className="mt-2 text-xs text-slate-700">{decision.reasons.join(" · ")}</p>{showDebug && <div className="mt-2 rounded-lg bg-slate-50 p-2 font-mono text-[10px] text-slate-600">lookAheadDepth={decision.lookAheadDepth} · resourcePenalty={decision.candidate.resourcePenalty.toFixed(1)} · hardRejected={String(decision.candidate.hardRejected)}</div>}</article>)}</div></section>}
    {timeline.length > 0 && <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold text-slate-900">Linha do tempo simulada</h2><p className="mt-1 text-xs text-slate-500">Prévia temporal por prensa. Gaps indicam possível espera entre decisões.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{Object.entries(Object.groupBy(timeline, (item) => item.press)).map(([press, blocks]) => <div key={press} className="rounded-xl border bg-slate-50 p-3"><p className="text-sm font-bold text-slate-900">Prensa {press}</p><div className="mt-2 space-y-2">{blocks?.map((block) => <div key={`${block.press}-${block.orderId}-${block.startAt}`} className="rounded-lg border border-blue-100 bg-white p-2 text-xs"><div className="flex justify-between gap-2"><strong>{request.orders.find(order => order.id === block.orderId)?.order ?? block.orderId}</strong><span>{Math.round(block.durationMinutes)} min</span></div><p className="text-slate-500">{new Date(block.startAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })} → {new Date(block.endAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}{block.gapBeforeMinutes > 0 ? ` · gap ${Math.round(block.gapBeforeMinutes)} min` : ""}</p></div>)}</div></div>)}</div></section>}
    {showDebug && candidateDebug.length > 0 && <section className="rounded-2xl border border-slate-300 bg-slate-50 p-5"><h2 className="font-bold text-slate-900">Diagnóstico de candidatos</h2><p className="mt-1 text-xs text-slate-500">Itens avaliados pelo motor e regras que impediram sua seleção.</p><div className="mt-3 max-h-72 space-y-2 overflow-auto">{candidateDebug.map((item, index) => <div key={`${item.candidate.orderId}-${item.candidate.press}-${index}`} className="flex items-start justify-between gap-3 rounded-lg border bg-white p-2 text-xs"><span><strong>{request.orders.find(order => order.id === item.candidate.orderId)?.order ?? item.candidate.orderId}</strong> · prensa {item.candidate.press}</span><span className={item.rejected ? "text-red-700" : "text-emerald-700"}>{item.rejected ? item.rejectionReasons.join("; ") : "Elegível"}</span></div>)}</div></section>}
    <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["OPs", result.metrics.orders], ["Programadas", result.metrics.scheduled], ["Pendências", result.metrics.pending], ["Congeladas", result.metrics.frozen], ["Prensas", result.metrics.presses], ["Kg restantes", result.metrics.totalKg.toLocaleString("pt-BR", { maximumFractionDigits: 1 })]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>)}</section>
    <section className={"rounded-2xl border p-5 " + (validation.length || result.dataIssues.length ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50")}><div className="flex items-center gap-2 font-semibold">{validation.length || result.dataIssues.length ? <AlertTriangle className="size-5 text-amber-600" /> : <CheckCircle2 className="size-5 text-emerald-600" />}{result.status === "pending-data" ? "Precisamos confirmar alguns dados" : "Programação pronta para análise"}</div><p className="mt-2 text-sm text-slate-700">{result.solverStatus === "baseline" ? "A programação atual foi mantida como está. Os avisos abaixo mostram o que precisa ser conferido antes de testar mudanças de prensa." : "Aguardando execução."}</p>{(result.dataIssues.length > 0 || validation.length > 0) && <ul className="mt-3 max-h-48 space-y-1 overflow-auto text-xs text-slate-700">{[...result.dataIssues.slice(0, 8), ...validation.slice(0, 8)].map(issue => <li key={issue}>• {humanizePlanningIssue(issue)}</li>)}</ul>}</section>
    <section className="overflow-hidden rounded-2xl border bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 px-5 py-4"><div><h2 className="font-bold">Carteira e zonas de programação</h2><p className="text-xs text-slate-500">Congelada não move · rolante recebe penalidade · livre poderá trocar de prensa na Fase 2.</p></div><span className="text-xs text-slate-500">Modelo {request.modelVersion}</span></header><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr>{["Zona", "OP / ferramenta", "Prensa atual", "Posição", "Saldo kg", "Elegibilidade", "Motivo"].map(label => <th key={label} className="whitespace-nowrap px-5 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{result.assignments.map(item => { const order = request.orders.find(candidate => candidate.id === item.orderId); return <tr key={item.orderId} className="border-b"><td className="px-5 py-3"><span className={"rounded-full px-2 py-1 text-xs font-medium " + (item.zone === "frozen" ? "bg-blue-100 text-blue-800" : item.zone === "rolling" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800")}>{item.zone === "frozen" ? "Congelada" : item.zone === "rolling" ? "Rolante" : "Livre"}</span></td><td className="px-5 py-3"><strong>{item.order}</strong><p className="text-xs text-slate-500">{item.tool}</p></td><td className="px-5 py-3">Prensa {item.press}</td><td className="px-5 py-3 font-mono">{item.position}</td><td className="px-5 py-3">{order?.remainingKg === null || order?.remainingKg === undefined ? "A confirmar" : order.remainingKg.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}</td><td className="px-5 py-3 text-xs">{order?.eligiblePresses.map(press => `Prensa ${press}`).join(" · ")}</td><td className="px-5 py-3 text-xs text-slate-600">{item.locked && <LockKeyhole className="mr-1 inline size-3" />}{item.reasons[0]}</td></tr>; })}</tbody></table></div></section>
    <footer className="rounded-xl border border-dashed bg-slate-50 p-4 text-xs text-slate-600">V3 em fundação: o baseline e o validador já estão separados. A próxima etapa conecta a matriz real de elegibilidade e então habilita a distribuição global entre as prensas 1.8 e 1.9 com OR-Tools. IA não participa do cálculo.</footer>
  </div>;
}
