"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Disc3, Loader2, Pencil, Plus, RefreshCw, TriangleAlert, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Resource { id: string; boCode: string; totalQuantity: number; unavailableQuantity: number; availableQuantity: number; status: "available" | "maintenance" | "blocked" | "inactive"; location: string | null; notes: string | null; }
type Draft = Omit<Resource,"totalQuantity"|"unavailableQuantity"|"availableQuantity"> & { totalQuantity: string; unavailableQuantity: string };
const blank=():Draft=>({id:"",boCode:"",totalQuantity:"1",unavailableQuantity:"0",status:"available",location:"",notes:""});
const labels={available:"Disponível",maintenance:"Manutenção",blocked:"Bloqueado",inactive:"Inativo"} as const;

export function BoResourcesManager(){
  const [items,setItems]=useState<Resource[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [draft,setDraft]=useState<Draft|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/bo-resources",{cache:"no-store"});const body=await response.json().catch(()=>null) as Resource[]|{error?:string}|null;if(!response.ok)throw new Error(body&&!Array.isArray(body)?body.error:"Não foi possível carregar os BOs.");setItems(Array.isArray(body)?body:[]);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar os BOs.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const totals=useMemo(()=>items.reduce((sum,item)=>({total:sum.total+item.totalQuantity,free:sum.free+item.availableQuantity,unavailable:sum.unavailable+item.unavailableQuantity}),{total:0,free:0,unavailable:0}),[items]);
  async function save(){if(!draft)return;setSaving(true);setError("");setNotice("");try{const response=await fetch("/api/bo-resources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,id:draft.id||null,totalQuantity:Number(draft.totalQuantity),unavailableQuantity:Number(draft.unavailableQuantity)})});const body=await response.json().catch(()=>null) as {error?:string}|null;if(!response.ok)throw new Error(body?.error||"Não foi possível salvar o BO.");setDraft(null);setNotice("BO salvo no estoque compartilhado e registrado na auditoria.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível salvar o BO.");}finally{setSaving(false);}}
  if(loading)return <div className="grid min-h-52 place-items-center rounded-2xl border bg-white"><Loader2 className="size-7 animate-spin text-orange-500"/></div>;
  return <div className="space-y-4">
    {error?<div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700"><TriangleAlert className="size-5"/><span className="flex-1">{error}</span><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="size-4"/>Atualizar</Button></div>:null}
    {notice?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{notice}</div>:null}
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="flex items-center gap-3 border-b px-5 py-4"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Disc3 className="size-5"/></span><div className="flex-1"><h2 className="font-heading text-lg font-black">BOs compartilhados da fábrica</h2><p className="text-sm text-slate-500">{totals.free} livre(s) de {totals.total} · {totals.unavailable} fora de uso. As duas prensas disputam o mesmo saldo.</p></div><Button className="bg-orange-600 text-white hover:bg-orange-700" onClick={()=>setDraft(blank())}><Plus className="size-4"/>Novo BO</Button></header>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">BO</th><th className="px-4 py-3">Local</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3 text-right">Fora de uso</th><th className="px-4 py-3 text-right">Livre</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Ação</th></tr></thead><tbody>{items.length?items.map(item=><tr key={item.id} className="border-t hover:bg-violet-50/30"><td className="px-5 py-3"><strong className="font-mono text-violet-700">BO {item.boCode}</strong><span className="block text-[10px] font-bold uppercase text-emerald-600">Uso compartilhado</span></td><td className="px-4 py-3 text-slate-500">{item.location||"—"}</td><td className="px-4 py-3 text-right font-bold">{item.totalQuantity}</td><td className="px-4 py-3 text-right text-amber-600">{item.unavailableQuantity}</td><td className="px-4 py-3 text-right text-lg font-black text-emerald-600">{item.availableQuantity}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">{labels[item.status]}</span></td><td className="px-5 py-3 text-right"><Button variant="ghost" size="sm" onClick={()=>setDraft({...item,totalQuantity:String(item.totalQuantity),unavailableQuantity:String(item.unavailableQuantity),location:item.location??"",notes:item.notes??""})}><Pencil className="size-4"/>Editar</Button></td></tr>):<tr><td colSpan={7} className="h-32 text-center text-slate-400">Cadastre os BOs físicos disponíveis na fábrica.</td></tr>}</tbody></table></div>
    </section>
    {draft?<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section className="w-full max-w-xl overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="flex items-start border-b px-5 py-4"><div className="flex-1"><h2 className="font-heading text-lg font-black">{draft.id?"Editar BO":"Cadastrar BO"}</h2><p className="text-xs text-slate-500">Informe a capacidade física compartilhada pelas duas prensas.</p></div><button type="button" onClick={()=>setDraft(null)}><X className="size-5"/></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Código do BO"><input autoFocus value={draft.boCode} onChange={event=>setDraft({...draft,boCode:event.target.value.toUpperCase()})} placeholder="Ex.: 6A"/></Field><Field label="Localização"><input value={draft.location??""} onChange={event=>setDraft({...draft,location:event.target.value})} placeholder="Ex.: Rack B"/></Field><Field label="Quantidade total"><input type="number" min="0" value={draft.totalQuantity} onChange={event=>setDraft({...draft,totalQuantity:event.target.value})}/></Field><Field label="Fora de uso"><input type="number" min="0" value={draft.unavailableQuantity} onChange={event=>setDraft({...draft,unavailableQuantity:event.target.value})}/></Field><Field label="Status"><select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value as Resource["status"]})}><option value="available">Disponível</option><option value="maintenance">Manutenção</option><option value="blocked">Bloqueado</option><option value="inactive">Inativo</option></select></Field><label className="text-sm font-bold sm:col-span-2">Observações<textarea rows={3} value={draft.notes??""} onChange={event=>setDraft({...draft,notes:event.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2 outline-none focus:border-orange-400"/></label></div><footer className="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><Button variant="outline" onClick={()=>setDraft(null)}>Cancelar</Button><Button disabled={saving||!draft.boCode.trim()} className="bg-orange-600 text-white hover:bg-orange-700" onClick={()=>void save()}>{saving?<Loader2 className="size-4 animate-spin"/>:<Disc3 className="size-4"/>}Salvar BO</Button></footer></section></div>:null}
  </div>;
}

function Field({label,children}:{label:string;children:React.ReactElement}){return <label className="text-sm font-bold">{label}<span className="[&>*]:mt-1.5 [&>*]:h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-white [&>*]:px-3 [&>*]:outline-none focus-within:[&>*]:border-orange-400">{children}</span></label>;}
