"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Edit3, Factory, Loader2, Plus, Save, Tags, Wrench, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type CatalogType = "occurrence_type" | "occurrence_area" | "occurrence_category" | "occurrence_cause" | "occurrence_action" | "occurrence_impact" | "occurrence_destination" | "occurrence_attachment_type" | "quality_defect" | "quality_cause" | "quality_disposition" | "maintenance_intervention" | "maintenance_cause" | "maintenance_priority" | "maintenance_destination" | "process_route" | "packaging_type" | "billet_supplier" | "alloy" | "cooling_mode" | "billet_casing";
type Catalog = { id: string; catalog_type: CatalogType; code: string; label: string; responsible_department: string | null; sort_order: number; is_active: boolean };
const catalogGroups: Array<{ key: string; title: string; description: string; icon: typeof Factory; types: Array<{ value: CatalogType; label: string }> }> = [
  { key: "process", title: "Processo e extrusão", description: "Parâmetros e listas usados na preparação, extrusão, resfriamento e embalagem.", icon: Factory, types: [{ value: "alloy", label: "Ligas e têmperas" }, { value: "cooling_mode", label: "Modos de resfriamento" }, { value: "process_route", label: "Rotas de processo" }, { value: "packaging_type", label: "Tipos de embalagem" }, { value: "billet_supplier", label: "Fornecedores de tarugo" }, { value: "billet_casing", label: "Carcaças de tarugo" }] },
  { key: "occurrence", title: "Report da Produção", description: "Contexto padronizado para registrar, direcionar e resolver ocorrências.", icon: Tags, types: [{ value: "occurrence_type", label: "Tipos" }, { value: "occurrence_area", label: "Áreas" }, { value: "occurrence_category", label: "Categorias" }, { value: "occurrence_cause", label: "Causas prováveis" }, { value: "occurrence_action", label: "Ações" }, { value: "occurrence_impact", label: "Impactos" }, { value: "occurrence_destination", label: "Destinos" }, { value: "occurrence_attachment_type", label: "Tipos de anexo" }] },
  { key: "quality", title: "Qualidade", description: "Defeitos, causas e disposições para controlar liberação e retrabalho.", icon: Tags, types: [{ value: "quality_defect", label: "Defeitos" }, { value: "quality_cause", label: "Causas" }, { value: "quality_disposition", label: "Disposições" }] },
  { key: "maintenance", title: "Manutenção", description: "Intervenções, causas, prioridades e equipamentos de destino.", icon: Wrench, types: [{ value: "maintenance_intervention", label: "Intervenções" }, { value: "maintenance_cause", label: "Causas" }, { value: "maintenance_priority", label: "Prioridades" }, { value: "maintenance_destination", label: "Destinos" }] },
];

export function OccurrenceCatalogManager() {
  const [items, setItems] = useState<Catalog[]>([]); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState<{ catalogType: CatalogType; code: string; label: string; department: string; sortOrder: string }>({ catalogType: "occurrence_type", code: "", label: "", department: "", sortOrder: "100" });
  const load = useCallback(async () => { const response = await fetch("/api/occurrence-catalogs", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) setMessage(payload.error || "Não foi possível carregar os cadastros industriais."); else setItems((payload.catalogs ?? []) as Catalog[]); }, []);
  useEffect(() => { void load(); }, [load]);
  const selectedTypeLabel = useMemo(() => catalogGroups.flatMap((group) => group.types).find((type) => type.value === form.catalogType)?.label ?? "Item", [form.catalogType]);
  async function create(event: React.FormEvent) { event.preventDefault(); if (!form.code.trim() || !form.label.trim()) return; setSaving(true); setMessage(""); try { const response = await fetch("/api/occurrence-catalogs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ catalogType: form.catalogType, code: form.code, label: form.label, department: form.department || null, sortOrder: Number(form.sortOrder) || 100 }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setForm((current) => ({ ...current, code: "", label: "", department: "" })); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível criar o item."); } finally { setSaving(false); } }
  async function toggle(item: Catalog) { setSaving(true); try { const response = await fetch("/api/occurrence-catalogs", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, isActive: !item.is_active }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível atualizar o item."); } finally { setSaving(false); } }
  async function saveEdit(item: Catalog) { setSaving(true); try { const response = await fetch("/api/occurrence-catalogs", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, label: item.label, department: item.responsible_department, sortOrder: item.sort_order }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setEditing(null); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar o item."); } finally { setSaving(false); } }
  const section = (group: (typeof catalogGroups)[number]) => { const Icon = group.icon; return <section key={group.key} className="rounded-2xl border bg-white shadow-sm"><div className="flex items-start gap-3 border-b px-5 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-orange-50 text-orange-600"><Icon className="size-5" /></span><div><h2 className="font-heading font-bold text-slate-900">{group.title}</h2><p className="text-sm text-slate-500">{group.description}</p></div></div><div className="grid gap-4 p-5 xl:grid-cols-2">{group.types.map((type) => { const rows = items.filter((item) => item.catalog_type === type.value); return <div key={type.value} className="overflow-hidden rounded-xl border bg-slate-50/50"><div className="border-b bg-white px-3 py-2"><p className="text-sm font-bold text-slate-800">{type.label}</p><p className="text-[11px] text-slate-400">Código estável · itens inativos ficam fora dos formulários.</p></div><div className="divide-y">{rows.map((item) => <div key={item.id} className="flex items-center gap-2 px-3 py-2.5"><div className="min-w-0 flex-1">{editing === item.id ? <div className="grid gap-2 sm:grid-cols-2"><Input value={item.label} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, label: event.target.value } : row))} /><Input value={item.responsible_department ?? ""} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, responsible_department: event.target.value } : row))} placeholder="Departamento" /></div> : <><p className={`text-sm font-semibold ${item.is_active ? "text-slate-800" : "text-slate-400 line-through"}`}>{item.label}</p><p className="text-[11px] text-slate-400">{item.code} · {item.responsible_department || "Sem responsável"}</p></>}</div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${item.is_active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{item.is_active ? "Ativo" : "Inativo"}</span>{editing === item.id ? <><Button size="icon-sm" variant="outline" onClick={() => void saveEdit(item)} disabled={saving}><Check className="size-4" /></Button><Button size="icon-sm" variant="ghost" onClick={() => setEditing(null)}><X className="size-4" /></Button></> : <><Button size="icon-sm" variant="ghost" onClick={() => setEditing(item.id)} aria-label={`Editar ${item.label}`}><Edit3 className="size-4" /></Button><Button size="sm" variant="outline" onClick={() => void toggle(item)} disabled={saving}>{item.is_active ? "Desativar" : "Ativar"}</Button></>}</div>)}{rows.length === 0 && <p className="p-3 text-xs text-slate-500">Nenhum item cadastrado ainda.</p>}</div></div>; })}</div></section>; };
  return <div className="space-y-5">{message && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{message}</div>}<form onSubmit={create} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Plus className="size-5 text-orange-600" /><div><h2 className="font-heading font-bold text-slate-900">Adicionar cadastro</h2><p className="text-sm text-slate-500">Cadastre opções sem alterar o código. Desativar preserva o histórico.</p></div></div><div className="grid gap-3 md:grid-cols-5"><select value={form.catalogType} onChange={(event) => setForm({ ...form, catalogType: event.target.value as CatalogType })} className="field-select md:col-span-2"><optgroup label="Processo e extrusão">{catalogGroups[0].types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</optgroup><optgroup label="Report da Produção">{catalogGroups[1].types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</optgroup><optgroup label="Qualidade">{catalogGroups[2].types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</optgroup><optgroup label="Manutenção">{catalogGroups[3].types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</optgroup></select><Input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase().replace(/\s+/g, "_") })} placeholder="Código estável" /><Input value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} placeholder={`Nome de ${selectedTypeLabel.toLocaleLowerCase()}`} /><Input value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} placeholder="Departamento" /><Button type="submit" disabled={saving || !form.code || !form.label}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />} Adicionar</Button></div></form><div className="space-y-5">{catalogGroups.map(section)}</div></div>;
}
