"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, Loader2, Pencil, Plus, RefreshCw, TriangleAlert, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Resource { id: string; machineCode: string; sharedAcrossMachines?: boolean; carcassCode: string; totalQuantity: number; unavailableQuantity: number; reservedQuantity: number; availableQuantity: number; status: "available" | "maintenance" | "blocked" | "inactive"; location: string | null; notes: string | null; }
type Draft = Omit<Resource, "reservedQuantity" | "availableQuantity" | "totalQuantity" | "unavailableQuantity"> & { totalQuantity: string; unavailableQuantity: string };
const blank = (): Draft => ({ id: "", machineCode: "SHARED", sharedAcrossMachines: true, carcassCode: "", totalQuantity: "1", unavailableQuantity: "0", status: "available", location: "", notes: "" });
const labels = { available: "Disponível", maintenance: "Manutenção", blocked: "Bloqueada", inactive: "Inativa" } as const;

export function PressResourcesManager() {
  const [items, setItems] = useState<Resource[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [draft, setDraft] = useState<Draft | null>(null);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await fetch("/api/press-resources", { cache: "no-store" }); const body = await response.json().catch(() => null) as Resource[] | { error?: string } | null; if (!response.ok) throw new Error(body && !Array.isArray(body) ? body.error : "Não foi possível carregar as carcaças."); setItems(Array.isArray(body) ? body : []); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar as carcaças."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const totals = useMemo(() => items.reduce((sum, item) => ({ total: sum.total + item.totalQuantity, free: sum.free + item.availableQuantity, unavailable: sum.unavailable + item.unavailableQuantity, reserved: sum.reserved + item.reservedQuantity }), { total: 0, free: 0, unavailable: 0, reserved: 0 }), [items]);
  const openEdit = (item: Resource) => setDraft({ ...item, totalQuantity: String(item.totalQuantity), unavailableQuantity: String(item.unavailableQuantity), location: item.location ?? "", notes: item.notes ?? "" });
  async function save() {
    if (!draft) return; setSaving(true); setError(""); setNotice("");
    try { const response = await fetch("/api/press-resources", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, id: draft.id || null, totalQuantity: Number(draft.totalQuantity), unavailableQuantity: Number(draft.unavailableQuantity) }) }); const body = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(body?.error || "Não foi possível salvar a carcaça."); setDraft(null); setNotice("Recurso salvo e registrado na auditoria."); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar a carcaça."); }
    finally { setSaving(false); }
  }
  if (loading) return <div className="grid min-h-72 place-items-center rounded-2xl border bg-white"><Loader2 className="size-7 animate-spin text-orange-500" /></div>;
  return <div className="space-y-4">
    {error ? <div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700"><TriangleAlert className="size-5" /><span className="flex-1">{error}</span><Button size="sm" variant="outline" onClick={() => void load()}><RefreshCw className="size-4" />Atualizar</Button></div> : null}
    {notice ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{notice}</div> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total físico", totals.total], ["Livres", totals.free], ["Em manutenção/bloqueadas", totals.unavailable], ["Reservadas", totals.reserved]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-slate-950">{value}</p></div>)}</section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="flex items-center gap-3 border-b px-5 py-4"><span className="grid size-10 place-items-center rounded-xl bg-orange-50 text-orange-600"><Boxes className="size-5" /></span><div className="flex-1"><h2 className="font-heading text-lg font-black">Estoque compartilhado de carcaças</h2><p className="text-sm text-slate-500">As mesmas unidades podem atender a Prensa 1.8 ou a Prensa 1.9. Reservas simultâneas consomem o mesmo saldo.</p></div><Button className="h-10 bg-orange-600 px-4 text-white hover:bg-orange-700" onClick={() => setDraft(blank())}><Plus className="size-4" />Nova carcaça</Button></header>
      <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Carcaça</th><th className="px-4 py-3">Local</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3 text-right">Fora de uso</th><th className="px-4 py-3 text-right">Reservada</th><th className="px-4 py-3 text-right">Livre</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Ação</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item.id} className="border-t hover:bg-orange-50/30"><td className="px-5 py-3"><strong className="font-mono text-orange-600">{item.carcassCode}</strong><span className="block text-[10px] font-bold uppercase text-emerald-600">Uso compartilhado</span></td><td className="px-4 py-3 text-slate-500">{item.location || "—"}</td><td className="px-4 py-3 text-right font-bold">{item.totalQuantity}</td><td className="px-4 py-3 text-right text-amber-600">{item.unavailableQuantity}</td><td className="px-4 py-3 text-right text-blue-600">{item.reservedQuantity}</td><td className="px-4 py-3 text-right text-lg font-black text-emerald-600">{item.availableQuantity}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">{labels[item.status]}</span></td><td className="px-5 py-3 text-right"><Button variant="ghost" size="sm" onClick={() => openEdit(item)}><Pencil className="size-4" />Editar</Button></td></tr>) : <tr><td colSpan={8} className="h-40 text-center text-slate-400">Nenhuma carcaça cadastrada.</td></tr>}</tbody></table></div>
    </section>
    {draft ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section className="w-full max-w-2xl overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="flex items-start gap-3 border-b px-5 py-4"><div className="flex-1"><h2 className="font-heading text-lg font-black">{draft.id ? "Editar carcaça" : "Cadastrar carcaça"}</h2><p className="text-xs text-slate-500">O saldo cadastrado atende às duas prensas e será disputado quando houver uso simultâneo.</p></div><button type="button" aria-label="Fechar" onClick={() => setDraft(null)} className="p-2"><X className="size-5" /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2">
      <Field label="Código da carcaça"><input autoFocus value={draft.carcassCode} onChange={(event) => setDraft({ ...draft, carcassCode: event.target.value.toUpperCase() })} placeholder="Ex.: 250X170" /></Field><Field label="Localização"><input value={draft.location ?? ""} onChange={(event) => setDraft({ ...draft, location: event.target.value })} placeholder="Ex.: Rack compartilhado A" /></Field><Field label="Quantidade física total"><input type="number" min="0" value={draft.totalQuantity} onChange={(event) => setDraft({ ...draft, totalQuantity: event.target.value })} /></Field><Field label="Quantidade fora de uso"><input type="number" min="0" value={draft.unavailableQuantity} onChange={(event) => setDraft({ ...draft, unavailableQuantity: event.target.value })} /></Field><p className="-mt-2 text-xs text-slate-500 sm:col-span-2">Informe como “fora de uso” somente unidades quebradas, bloqueadas ou em manutenção. Unidades disponíveis devem permanecer em zero neste campo.</p><Field label="Status do conjunto"><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as Resource["status"] })}><option value="available">Disponível</option><option value="maintenance">Manutenção</option><option value="blocked">Bloqueada</option><option value="inactive">Inativa</option></select></Field><div className="rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-800"><strong className="block">Atende às duas prensas</strong>Não é necessário escolher uma prensa.</div><label className="sm:col-span-2 text-sm font-bold">Observações<textarea rows={3} value={draft.notes ?? ""} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} className="mt-1.5 w-full rounded-xl border px-3 py-2 outline-none focus:border-orange-400" /></label>
    </div><footer className="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><Button variant="outline" onClick={() => setDraft(null)}>Cancelar</Button><Button disabled={saving || !draft.carcassCode.trim()} className="bg-orange-600 text-white hover:bg-orange-700" onClick={() => void save()}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Boxes className="size-4" />}Salvar</Button></footer></section></div> : null}
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactElement }) { return <label className="text-sm font-bold">{label}<span className="[&>*]:mt-1.5 [&>*]:h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-white [&>*]:px-3 [&>*]:outline-none focus-within:[&>*]:border-orange-400">{children}</span></label>; }
