"use client";

import { useCallback, useEffect, useState } from "react";
import { CalendarClock, Loader2, Pencil, Plus, TriangleAlert, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Period { id: string; resourceType: "press" | "oven" | "tool" | "carcass"; resourceCode: string; startsAt: string; endsAt: string; reason: string; status: "active" | "cancelled"; notes: string | null; }
interface Draft extends Omit<Period, "startsAt" | "endsAt" | "notes"> { startsAt: string; endsAt: string; notes: string; }
const pad = (value: number) => String(value).padStart(2, "0");
const localValue = (date: Date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
const blank = (): Draft => { const start = new Date(); start.setMinutes(Math.ceil(start.getMinutes() / 30) * 30, 0, 0); const end = new Date(start.getTime() + 60 * 60_000); return { id: "", resourceType: "press", resourceCode: "18", startsAt: localValue(start), endsAt: localValue(end), reason: "", status: "active", notes: "" }; };
const resourceLabel = { press: "Prensa", oven: "Forno", tool: "Ferramenta", carcass: "Carcaça" } as const;

export function ResourceCalendarManager() {
  const [periods, setPeriods] = useState<Period[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [draft, setDraft] = useState<Draft | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/resource-calendar", { cache: "no-store" }); const body = await response.json().catch(() => null) as Period[] | { error?: string } | null; if (!response.ok) throw new Error(body && !Array.isArray(body) ? body.error : "Não foi possível carregar o calendário."); setPeriods(Array.isArray(body) ? body : []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o calendário."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const edit = (period: Period) => setDraft({ ...period, startsAt: localValue(new Date(period.startsAt)), endsAt: localValue(new Date(period.endsAt)), notes: period.notes ?? "" });
  async function save() { if (!draft) return; setSaving(true); setError(""); try { const response = await fetch("/api/resource-calendar", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, id: draft.id || null, startsAt: new Date(draft.startsAt).toISOString(), endsAt: new Date(draft.endsAt).toISOString() }) }); const body = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(body?.error || "Não foi possível salvar."); setDraft(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar."); } finally { setSaving(false); } }
  return <section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm">
    <header className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><CalendarClock className="size-5" /></span><div className="flex-1"><h2 className="font-heading font-bold text-slate-900">Calendário de indisponibilidades</h2><p className="text-sm text-slate-500">Bloqueios planejados de prensa são retirados automaticamente do tempo produtivo da simulação.</p></div><Button onClick={() => setDraft(blank())} className="bg-orange-500 hover:bg-orange-600"><Plus className="size-4" />Nova indisponibilidade</Button></header>
    {error ? <div className="m-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><TriangleAlert className="size-4" />{error}</div> : null}
    {loading ? <div className="grid h-32 place-items-center"><Loader2 className="size-6 animate-spin text-orange-500" /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Recurso</th><th className="px-4 py-3">Início</th><th className="px-4 py-3">Fim</th><th className="px-4 py-3">Motivo</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Ação</th></tr></thead><tbody>{periods.length ? periods.map((period) => <tr key={period.id} className="border-t"><td className="px-5 py-3"><strong>{resourceLabel[period.resourceType]}</strong><span className="block font-mono text-xs text-orange-600">{period.resourceCode}</span></td><td className="px-4 py-3 tabular-nums">{new Date(period.startsAt).toLocaleString("pt-BR")}</td><td className="px-4 py-3 tabular-nums">{new Date(period.endsAt).toLocaleString("pt-BR")}</td><td className="px-4 py-3 font-semibold">{period.reason}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${period.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{period.status === "active" ? "Ativa" : "Cancelada"}</span></td><td className="px-5 py-3 text-right"><Button size="sm" variant="ghost" onClick={() => edit(period)}><Pencil className="size-4" />Editar</Button></td></tr>) : <tr><td colSpan={6} className="h-32 text-center text-slate-400">Nenhuma indisponibilidade planejada.</td></tr>}</tbody></table></div>}
    {draft ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section className="w-full max-w-2xl overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="flex items-start border-b px-5 py-4"><div className="flex-1"><h2 className="font-heading text-lg font-black">Indisponibilidade planejada</h2><p className="text-xs text-slate-500">O período ficará fora das janelas produtivas da prensa.</p></div><button type="button" aria-label="Fechar" onClick={() => setDraft(null)} className="p-2"><X className="size-5" /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Tipo"><select value={draft.resourceType} disabled><option value="press">Prensa</option></select></Field><Field label="Prensa"><select value={draft.resourceCode} onChange={(event) => setDraft({ ...draft, resourceCode: event.target.value })}><option value="18">Prensa 1.8</option><option value="19">Prensa 1.9</option></select></Field><Field label="Início"><input type="datetime-local" value={draft.startsAt} onChange={(event) => setDraft({ ...draft, startsAt: event.target.value })} /></Field><Field label="Fim"><input type="datetime-local" value={draft.endsAt} onChange={(event) => setDraft({ ...draft, endsAt: event.target.value })} /></Field><Field label="Motivo"><input value={draft.reason} onChange={(event) => setDraft({ ...draft, reason: event.target.value })} placeholder="Ex.: manutenção preventiva" /></Field><Field label="Status"><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as Period["status"] })}><option value="active">Ativa</option><option value="cancelled">Cancelada</option></select></Field><label className="sm:col-span-2 text-sm font-bold">Observações<textarea rows={3} value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} className="mt-1.5 w-full rounded-xl border px-3 py-2 outline-none" /></label></div><footer className="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><Button variant="outline" onClick={() => setDraft(null)}>Cancelar</Button><Button disabled={saving || !draft.reason.trim() || !draft.resourceCode.trim()} onClick={() => void save()}>{saving ? <Loader2 className="size-4 animate-spin" /> : <CalendarClock className="size-4" />}Salvar período</Button></footer></section></div> : null}
  </section>;
}
function Field({ label, children }: { label: string; children: React.ReactElement }) { return <label className="text-sm font-bold">{label}<span className="[&>*]:mt-1.5 [&>*]:h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-white [&>*]:px-3 [&>*]:outline-none focus-within:[&>*]:border-orange-400">{children}</span></label>; }
