export interface LoadHelpTopic {
  title: string; summary: string; effect: string; example?: string; steps: string[];
}
const topic = (title: string, summary: string, effect: string, steps: string[], example?: string): LoadHelpTopic => ({ title, summary, effect, steps, example });
const compare = ["Altere o valor e clique em Testar impacto.", "Clique em Gerar alternativas para testar outras sequências.", "Compare os atrasos e as esperas antes de usar uma alternativa."];
export const loadHelp = {
  legacyScore: topic("Nota da Inteligência explicável", "Mostra a composição da nota histórica da simulação.", "Os pesos dessa nota são percentuais e precisam somar 100. São diferentes dos pesos de preferência da Central de Decisões. Uma nota alta não elimina impedimentos.", ["Abra a composição da nota para ver o motivo de cada resultado.", "Ao ajustar os percentuais, confira se a soma é 100%.", "Revise os impedimentos antes de aprovar."]),
  overview: topic("Como usar Carga Máquina", "Teste a ordem de produção antes de decidir o que executar.", "Esta tela calcula uma previsão com os dados cadastrados. Testar uma sequência não inicia nem aprova a produção.", ["Confira a prensa e o início da simulação.", "Abra os impedimentos e confira ferramentas, carcaças, BOs e material.", "Gere alternativas e compare os resultados.", "Use a sequência escolhida na simulação e revise os avisos.", "Salve o cenário. A aprovação é uma ação separada."]),
  weights: topic("Pesos dos objetivos", "O peso indica a importância de cada objetivo na comparação.", "Use valores de 0 a 100. Eles não precisam somar 100. Zero retira a penalização daquele objetivo, mas não libera um recurso indisponível.", compare, "Exemplo: aumentar o peso do atraso faz o sistema dar mais importância a reduzir atrasos. Não garante que todos os pedidos terminarão no prazo."),
  lateMinutes: topic("Atraso dos pedidos", "Compara quantos minutos as ordens terminam depois do prazo informado.", "Um peso maior dá mais importância a reduzir o atraso total. Sem prazo cadastrado, não é possível conferir a entrega.", compare),
  setupMinutes: topic("Preparação inicial e troca de liga", "A preparação inicial ocorre uma vez antes da primeira ferramenta; a troca de liga só é somada quando a liga muda.", "Um peso maior dá mais importância a reduzir esse tempo. Ele não muda as durações cadastradas.", compare),
  thermalMinutes: topic("Espera por ferramenta quente", "É a espera da prensa até a ferramenta estar pronta para uso.", "Um peso maior dá mais importância a evitar essa espera. O tempo de aquecimento continua sendo o cadastrado.", compare),
  resourceMinutes: topic("Espera por recursos", "É a espera por ferramenta, carcaça ou BO que está ocupado ou indisponível por um período.", "Um peso maior dá mais importância a diminuir a espera. Aumentar o peso não cria peças no estoque.", compare),
  shortRuns: topic("Corridas curtas seguidas", "São ordens pequenas e rápidas colocadas uma depois da outra.", "O sistema considera volume e duração juntos. A penalização começa quando a sequência ultrapassa o máximo configurado.", compare),
  highHoles: topic("Muitos furos seguidos", "Compara sequências de ferramentas que atingem o limite de furos definido abaixo.", "Um peso maior dá mais importância a reduzir sequências acima do máximo permitido pelo perfil.", compare),
  handoverHighHoles: topic("Furos no revezamento", "Conta ferramentas acima do limite de furos que extrudam entre 11:00 e 13:30, quando a equipe está reduzida.", "Um peso maior faz o motor preferir outra ferramenta nesse período quando houver alternativa viável. Não bloqueia uma ordem sem substituta.", compare, "O limite padrão é 2 furos; ele pode ser ajustado até 4 conforme a capacidade da mesa e da equipe."),
  remainderKg: topic("Sobra de tarugo", "É o saldo calculado depois do consumo das ordens da simulação.", "Um peso maior dá mais importância a reduzir essa sobra. A sobra calculada não significa, por si só, sucata ou perda.", compare),
  makespanMinutes: topic("Tempo até terminar a carga", "É o tempo decorrido até a última prensa terminar.", "Inclui o efeito do calendário. Um peso maior favorece alternativas que terminam mais cedo.", compare),
  lowVolumeKg: topic("Volume baixo (kg)", "Define abaixo de qual quantidade uma ordem pode ser considerada curta.", "A quantidade precisa estar abaixo deste valor e a duração abaixo do limite de corrida curta.", compare, "Exemplo: com 300 kg e 30 min, uma ordem de 200 kg e 20 min atende aos dois limites. Uma de 400 kg e 20 min não atende."),
  shortRunMinutes: topic("Corrida curta (min)", "Define abaixo de quantos minutos uma produção pode ser considerada curta.", "É o tempo de produção líquida, sem preparação e espera. O limite de volume também precisa ser atendido.", compare),
  maxConsecutiveShortRuns: topic("Máximo de corridas curtas seguidas", "Define quantas ordens curtas podem aparecer juntas antes da penalização.", "Conta separadamente em cada prensa. Uma ordem que não é curta interrompe a contagem.", compare, "Exemplo: com máximo 2, a terceira ordem curta seguida passa a contar como excesso."),
  highHolesThreshold: topic("Furos considerados altos", "Define a partir de quantos furos uma ferramenta entra no grupo de muitos furos.", "Ferramentas com quantidade igual ou maior entram na contagem. Isso não altera o cadastro da ferramenta.", compare, "Exemplo: com limite 4, ferramentas de 4, 6 ou 8 furos entram nesse grupo."),
  maxConsecutiveHighHoles: topic("Máximo de muitos furos seguidos", "Define quantas ferramentas do grupo de muitos furos podem aparecer juntas.", "A próxima ferramenta acima desse máximo passa a contar como excesso. A contagem é feita por prensa.", compare),
  handoverMaxHoles: topic("Máximo de furos no revezamento", "Define o máximo recomendado de furos durante o revezamento de 11:00 a 13:30.", "Ferramentas acima desse limite recebem uma penalização de preferência para reduzir o risco de mesa cheia com equipe reduzida. O limite pode variar de 2 a 4.", compare),
  profile: topic("Perfil de decisão", "Reúne pesos, limites e critérios usados para comparar os cenários.", "Selecionar um perfil inicial carrega uma proposta no editor. Aplicar usa os valores na simulação. Salvar versão guarda uma cópia no histórico.", ["Escolha o perfil e revise os valores.", "Teste o impacto.", "Aplique na simulação para comparar a carga.", "Para guardar, informe o motivo e salve a versão com acesso de administrador."]),
  custom: topic("Modo avançado e critérios", "Permite criar uma condição para avaliar as ordens.", "Todas as condições da mesma regra precisam ser verdadeiras. Uma regra obrigatória impede a aprovação; uma preferência afeta a comparação.", ["Dê um nome que explique o problema.", "Escolha o tipo e as condições.", "Defina quantas ordens seguidas acionam a regra.", "Teste o impacto antes de salvar."]),
  penalty: topic("Penalidade e peso do critério", "Definem quanto uma regra atendida pesa na comparação.", "A contribuição é a penalidade multiplicada pelo peso e dividida por 100. Regras obrigatórias bloqueiam mesmo com peso zero; regras informativas não penalizam.", compare, "Exemplo: penalidade 40 e peso 50 geram contribuição 20 antes da normalização da nota."),
  priority: topic("Prioridade do critério", "Organiza a apresentação das orientações da regra.", "1 aparece antes de 5. A prioridade não substitui o peso nem elimina impedimentos.", ["Use 1 para a orientação que deve aparecer primeiro.", "Use peso e penalidade para ajustar a comparação.", "Teste antes de salvar."]),
  score: topic("Nota e impedimentos", "A nota ajuda a comparar cenários avaliados com o mesmo perfil.", "Uma nota alta não autoriza produção. Recursos faltando ou dados não confirmados continuam exigindo conferência.", ["Leia os impedimentos antes da nota.", "Compare alternativas com o mesmo perfil.", "Confira os resultados calculados e as pendências."]),
  save: topic("Testar, aplicar e salvar", "Cada botão tem uma função diferente.", "Testar mostra a avaliação. Aplicar usa o perfil na simulação. Salvar versão guarda o perfil. Salvar cenário guarda a carga calculada. Nenhuma dessas ações inicia a produção.", ["Teste o impacto após mudar os campos.", "Aplique o perfil na simulação.", "Gere alternativas se quiser mudar a sequência.", "Salve o perfil com um motivo e salve o cenário separadamente."]),
  carcass: topic("Carcaça cadastrada e carcaça livre", "O modelo exigido pela ferramenta é diferente da quantidade disponível no estoque físico.", "Ter a medida cadastrada não significa ter uma unidade livre. A sequência física da ferramenta também precisa corresponder.", ["Confira a ferramenta e sua sequência física.", "Confira Diâmetro e Medida Pacote no cadastro.", "Confira a quantidade livre e as reservas no estoque.", "Atualize e calcule novamente."], "Exemplo de medida: diâmetro 250 mm e pacote 170 mm formam a carcaça 250x170."),
  productivity: topic("Produtividade (kg/h)", "É a quantidade estimada que a ferramenta produz em uma hora.", "O cálculo usa valores válidos até 2.500 kg/h. Quando não há valor válido, usa 1.300 kg/h como estimativa, não como medição.", ["Confira a origem do valor: arquivo, cadastro ou estimativa.", "Se houver divergência, confira o registro de produção.", "Recalcule após corrigir o dado."]),
  activeLoad: topic("Carga ativa", "É a quantidade que ainda falta produzir nas ordens selecionadas.", "Não é a quantidade bruta de tarugo. O consumo de material considera a eficiência cadastrada.", ["Confira as ordens selecionadas e o saldo a produzir.", "Veja Barras a preparar para conferir o material."]),
  netTime: topic("Produção líquida: soma das prensas", "Soma o tempo de produção das prensas, sem preparação ou espera.", "As prensas podem trabalhar juntas. Por isso, essa soma não é o tempo no relógio até terminar tudo.", ["Use este indicador para consultar o trabalho de produção.", "Veja Término simulado para saber quando a carga termina."], "Exemplo: duas prensas trabalhando 1 hora ao mesmo tempo somam 2 horas de produção, mas passam apenas 1 hora no relógio."),
  end: topic("Término simulado", "É a previsão de quando a última prensa termina a carga.", "Considera a sequência, os turnos, as preparações e as esperas calculadas. Pode mudar quando os dados forem atualizados.", ["Confira a data de início e os turnos.", "Revise os avisos de recursos e aquecimento.", "Compare o término das alternativas."]),
  bars: topic("Barras a preparar", "É a quantidade calculada de barras de tarugo para atender à carga.", "Considera peso das barras, eficiência e saldo calculado por liga. Não é uma confirmação de estoque livre.", ["Confira a necessidade por liga.", "Compare com o estoque disponível.", "Resolva faltas antes de aprovar."]),
  items: topic("Itens na sequência", "Conta as ordens que ainda têm quantidade a produzir na seleção atual.", "Uma mesma ferramenta pode aparecer em mais de uma ordem.", ["Confira o filtro de prensa.", "Abra a tabela para consultar as ordens."]),
  sequence: topic("FIFO, sugerida e manual", "São maneiras diferentes de organizar as ordens.", "FIFO usa a sequência de entrada do cálculo. Sugerida usa a heurística do simulador. Manual permite testar uma ordem escolhida pelo usuário. Gerar alternativas na Central compara outras estratégias.", ["Escolha o modo.", "Compare os horários e impedimentos.", "Salve um cenário se quiser guardar a comparação."]),
  learning: topic("Aprendizado operacional", "Compara registros reais para ajudar a avaliar previsões.", "Sem previsão comparada com produção real, a precisão ainda não foi medida. Quantidade de registros não é garantia de acerto.", ["Registre início, fim e quantidade real.", "Confira a produtividade dos registros.", "Compare a previsão com o resultado real."]),
  ai: topic("Copiloto de decisão", "Explica os dados da simulação e pode propor outra sequência para avaliação.", "A IA pode falhar ou não responder. As regras calculadas continuam disponíveis. A proposta precisa ser recalculada e conferida antes da aprovação.", ["Leia o problema e os passos sugeridos.", "Confira os dados ausentes.", "Teste a sequência proposta e compare os resultados."]),
} satisfies Record<string, LoadHelpTopic>;
export type LoadHelpKey = keyof typeof loadHelp;
export function findLoadHelp(query: string) {
  const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const terms = normalize(query).trim().split(/\s+/);
  return (Object.entries(loadHelp) as [LoadHelpKey, LoadHelpTopic][]).filter(([,item]) =>
    terms.every(term => normalize([item.title,item.summary,item.effect,item.example,...item.steps].join(" ")).includes(term)));
}
